// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "exportRoot": string;
      "cachePath": string;
      "paperFolderFormat": string;
      "enabledCollections": string;
      "exportPdf": boolean;
      "exportKimi": boolean;
      "exportBibtex": boolean;
      "exportNotes": boolean;
      "exportArxivId": boolean;
      "pdfMode": string;
      "linkBackToZotero": boolean;
      "autoSync": boolean;
      "pipelineServiceUrl": string;
      "exportLatex": boolean;
      "exportPipelinePdf": boolean;
    };
  }
}
