import { getPref } from "../utils/prefs";
import {
  ensureDir,
  joinPath,
  formatPaperFolder,
  getCachePath,
  cleanDirectory,
  removeDir,
} from "./utils";
import { extractArxivId, stripVersion } from "./arxiv-id";
import { ExportContext, ProviderResult } from "./content-providers/provider";
import { getEnabledProviders } from "./content-providers/registry";
import {
  buildCollectionTree,
  resolveItemPaths,
  flattenTree,
  getExportRoot,
  CollectionNode,
} from "./tree-builder";

// ---------------------------------------------------------------------------
// Progress callback for fullRebuild
// ---------------------------------------------------------------------------

export type RebuildProgressCallback = (info: {
  current: number;
  total: number;
  arxivId: string;
  title: string;
  status: "exporting" | "done" | "error";
}) => void;

// ---------------------------------------------------------------------------
// Index types — tracks what has been exported and where
// ---------------------------------------------------------------------------

interface IndexEntry {
  /** Zotero item ID */
  itemId: number;
  /** arXiv ID (version-stripped) */
  arxivId: string;
  /** Paper folder name (from formatPaperFolder) */
  folderName: string;
  /** All directories where this paper's folder exists */
  exportedPaths: string[];
  /** Files generated by providers (relative to paper folder) */
  files: string[];
  /** Timestamp of last export */
  lastExported: number;
}

interface ExportIndex {
  /** Schema version for forward compatibility */
  version: number;
  /** Map of itemId (as string key) → IndexEntry */
  entries: Record<string, IndexEntry>;
}

// ---------------------------------------------------------------------------
// Export queue — debounced, concurrency-limited task queue
// ---------------------------------------------------------------------------

interface QueueTask {
  itemId: number;
  resolve: (value: void) => void;
  reject: (reason: any) => void;
}

/**
 * ExportQueue batches and rate-limits export operations.
 *
 * - Debounce: waits `debounceMs` after the last enqueue before flushing
 * - Concurrency: runs at most `maxConcurrency` exports in parallel
 * - Deduplication: multiple enqueues for the same itemId share one task;
 *   all callers' promises resolve/reject together
 */
class ExportQueue {
  private pending = new Map<number, QueueTask[]>();
  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private debounceGeneration = 0;
  private activeCount = 0;
  private queue: QueueTask[] = [];
  private maxConcurrency: number;
  private debounceMs: number;
  private processor: (itemId: number) => Promise<void>;

  constructor(
    processor: (itemId: number) => Promise<void>,
    maxConcurrency = 3,
    debounceMs = 500,
  ) {
    this.processor = processor;
    this.maxConcurrency = maxConcurrency;
    this.debounceMs = debounceMs;
  }

  /**
   * Enqueue an item for export. Returns a promise that resolves
   * when the export completes (or rejects on failure).
   */
  enqueue(itemId: number): Promise<void> {
    return new Promise((resolve, reject) => {
      const task: QueueTask = { itemId, resolve, reject };

      // Group tasks for the same itemId so we only process once
      if (!this.pending.has(itemId)) {
        this.pending.set(itemId, []);
      }
      this.pending.get(itemId)!.push(task);

      // Reset debounce timer using a generation counter
      // (old timer callbacks check the generation and become no-ops)
      const gen = ++this.debounceGeneration;
      this.debounceTimer = setTimeout(() => {
        // Only flush if this is still the latest generation
        if (gen === this.debounceGeneration) {
          this.debounceTimer = null;
          this.flush();
        }
      }, this.debounceMs);
    });
  }

  /**
   * Flush all pending tasks into the processing queue.
   * Merges multiple enqueues for the same itemId into a single task
   * whose resolution fans out to all original callers.
   */
  private flush(): void {
    for (const [itemId, tasks] of this.pending) {
      const combinedTask: QueueTask = {
        itemId,
        resolve: () => tasks.forEach((t) => t.resolve()),
        reject: (err) => tasks.forEach((t) => t.reject(err)),
      };
      this.queue.push(combinedTask);
    }
    this.pending.clear();
    this.processNext();
  }

  /**
   * Pull tasks from the queue and execute them up to maxConcurrency.
   */
  private processNext(): void {
    while (this.activeCount < this.maxConcurrency && this.queue.length > 0) {
      const task = this.queue.shift()!;
      this.activeCount++;

      this.processor(task.itemId)
        .then(() => task.resolve())
        .catch((err) => task.reject(err))
        .finally(() => {
          this.activeCount--;
          this.processNext();
        });
    }
  }
}

// ---------------------------------------------------------------------------
// Exporter — main export orchestrator
// ---------------------------------------------------------------------------

/**
 * The main exporter that coordinates collection tree building,
 * content provider execution, and filesystem management.
 *
 * - fullRebuild()      — wipe + re-export everything (settings change, manual)
 * - exportItem()       — incremental single-item export via debounced queue
 * - removeItemExport() — delete exported folders for trashed/deleted items
 */
export class Exporter {
  private exportQueue: ExportQueue;
  private indexCache: ExportIndex | null = null;

  constructor() {
    this.exportQueue = new ExportQueue(
      (itemId) => this.doExportItem(itemId),
      3, // max concurrency
      500, // debounce ms
    );
  }

  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  /**
   * Incremental rebuild (default): compare existing index with current
   * Zotero state. Only export new/changed items and remove stale ones.
   * Much faster than fullRebuild when most items already exist.
   *
   * @param onProgress Optional callback invoked per-item with progress info
   */
  async incrementalRebuild(onProgress?: RebuildProgressCallback): Promise<{
    exported: number;
    skipped: number;
    removed: number;
    errors: string[];
  }> {
    const exportRoot = getExportRoot();
    if (!exportRoot) {
      throw new Error("Export root path is not configured");
    }

    ztoolkit.log("[ZoFiles] Starting incremental rebuild...");
    await ensureDir(exportRoot);

    // Load existing index (may be empty on first run)
    const index = await this.loadIndex(exportRoot);

    // Build current collection tree
    const tree = await buildCollectionTree();
    const allNodes = flattenTree(tree);

    // Collect all current item IDs from tree
    const currentItemIds = new Set<number>();
    for (const node of allNodes) {
      for (const id of node.itemIds) {
        currentItemIds.add(id);
      }
    }

    // Determine what to do:
    // 1. Items in currentItemIds but NOT in index → need export
    // 2. Items in index but NOT in currentItemIds → need removal
    // 3. Items in both → check if folder name or paths changed
    //    3a. Paths changed → re-export (and clean old paths)
    //    3b. Item no longer in any collection → remove entirely
    const toExport: number[] = [];
    const toRemove: number[] = [];
    const toCleanAndReExport: number[] = [];
    const toCleanOnly: number[] = [];
    const upToDate: number[] = [];

    for (const itemId of currentItemIds) {
      const entry = index.entries[String(itemId)];
      if (!entry) {
        // New item — needs export
        toExport.push(itemId);
        continue;
      }

      // Check if the item's expected folder name has changed
      const item = Zotero.Items.get(itemId);
      if (!item || !item.isRegularItem()) continue;

      const rawId = extractArxivId(item);
      if (!rawId) continue;
      const arxivId = stripVersion(rawId);
      const expectedFolderName = formatPaperFolder(item, arxivId);
      const expectedPaths = resolveItemPaths(itemId, tree, exportRoot);

      if (expectedPaths.length === 0) {
        // Item no longer in any exported collection → remove its export
        toCleanOnly.push(itemId);
        continue;
      }

      // Re-export if folder name changed or target paths changed
      const pathsMatch =
        expectedPaths.length === entry.exportedPaths.length &&
        expectedPaths.every((p) => entry.exportedPaths.includes(p));

      if (entry.folderName !== expectedFolderName || !pathsMatch) {
        toCleanAndReExport.push(itemId);
      } else {
        // Check if the primary folder still exists on disk
        const primaryDir = expectedPaths[0];
        if (primaryDir) {
          const paperDir = joinPath(primaryDir, expectedFolderName);
          const exists = await IOUtils.exists(paperDir);
          if (!exists) {
            toExport.push(itemId);
          } else {
            upToDate.push(itemId);
          }
        } else {
          upToDate.push(itemId);
        }
      }
    }

    // Find stale items in index that are no longer in Zotero
    for (const key of Object.keys(index.entries)) {
      const itemId = parseInt(key, 10);
      if (!currentItemIds.has(itemId)) {
        toRemove.push(itemId);
      }
    }

    ztoolkit.log(
      `[ZoFiles] Incremental: ${toExport.length} new, ${toCleanAndReExport.length} changed, ${toCleanOnly.length} orphaned, ${upToDate.length} up-to-date, ${toRemove.length} stale`,
    );

    // --- Phase 1: Remove stale items (no longer in Zotero at all) ---
    let removed = 0;
    for (const itemId of toRemove) {
      const entry = index.entries[String(itemId)];
      if (entry) {
        for (const exportedPath of entry.exportedPaths) {
          const paperDir = joinPath(exportedPath, entry.folderName);
          try {
            await removeDir(paperDir);
          } catch {
            // Ignore
          }
        }
        delete index.entries[String(itemId)];
        removed++;
      }
    }

    // --- Phase 2: Clean items no longer in any exported collection ---
    for (const itemId of toCleanOnly) {
      const entry = index.entries[String(itemId)];
      if (entry) {
        ztoolkit.log(
          `[ZoFiles] Removing orphaned export for ${entry.arxivId} (item ${itemId})`,
        );
        for (const exportedPath of entry.exportedPaths) {
          const paperDir = joinPath(exportedPath, entry.folderName);
          try {
            await removeDir(paperDir);
          } catch {
            // Ignore
          }
        }
        delete index.entries[String(itemId)];
        removed++;
      }
    }

    // --- Phase 3: Clean old paths for items whose paths changed, then re-export ---
    for (const itemId of toCleanAndReExport) {
      const entry = index.entries[String(itemId)];
      if (entry) {
        ztoolkit.log(
          `[ZoFiles] Paths changed for ${entry.arxivId} (item ${itemId}), cleaning old locations`,
        );
        for (const exportedPath of entry.exportedPaths) {
          const paperDir = joinPath(exportedPath, entry.folderName);
          try {
            await removeDir(paperDir);
          } catch {
            // Ignore
          }
        }
        delete index.entries[String(itemId)];
      }
    }

    // --- Phase 4: Export new items + items with changed paths ---
    const allToExport = [...toExport, ...toCleanAndReExport];
    const errors: string[] = [];
    let exported = 0;
    let current = 0;

    for (const itemId of allToExport) {
      current++;

      let arxivIdForProgress = "unknown";
      let titleForProgress = "";
      try {
        const item = Zotero.Items.get(itemId);
        if (item) {
          arxivIdForProgress = extractArxivId(item) || "unknown";
          if (arxivIdForProgress !== "unknown") {
            arxivIdForProgress = stripVersion(arxivIdForProgress);
          }
          titleForProgress = String(item.getField("title") || "");
        }
      } catch {
        // Ignore
      }

      if (onProgress) {
        onProgress({
          current,
          total: allToExport.length,
          arxivId: arxivIdForProgress,
          title: titleForProgress,
          status: "exporting",
        });
      }

      try {
        await this.doExportItem(itemId, tree);
        exported++;
        if (onProgress) {
          onProgress({
            current,
            total: allToExport.length,
            arxivId: arxivIdForProgress,
            title: titleForProgress,
            status: "done",
          });
        }
      } catch (err: any) {
        errors.push(`Item ${itemId}: ${err.message || err}`);
        if (onProgress) {
          onProgress({
            current,
            total: allToExport.length,
            arxivId: arxivIdForProgress,
            title: titleForProgress,
            status: "error",
          });
        }
      }
    }

    await this.saveIndex(exportRoot);

    ztoolkit.log(
      `[ZoFiles] Incremental rebuild complete: ${exported} exported, ${upToDate.length} skipped, ${removed} removed, ${errors.length} errors`,
    );

    return { exported, skipped: upToDate.length, removed, errors };
  }

  /**
   * Force full rebuild: clean the export root completely and re-export
   * every item from scratch. Use when incremental rebuild has issues or
   * the user wants a clean slate.
   *
   * @param onProgress Optional callback invoked per-item with progress info
   */
  async fullRebuild(
    onProgress?: RebuildProgressCallback,
  ): Promise<{ exported: number; errors: string[] }> {
    const exportRoot = getExportRoot();
    if (!exportRoot) {
      throw new Error("Export root path is not configured");
    }

    ztoolkit.log("[ZoFiles] Starting full rebuild...");

    // Clean the export root (remove all contents, keep the dir)
    await cleanDirectory(exportRoot);
    await ensureDir(exportRoot);

    // Reset index
    this.indexCache = createEmptyIndex();

    // Build collection tree
    const tree = await buildCollectionTree();
    const allNodes = flattenTree(tree);

    // Collect all unique item IDs from the tree
    const itemIdSet = new Set<number>();
    for (const node of allNodes) {
      for (const id of node.itemIds) {
        itemIdSet.add(id);
      }
    }

    const total = itemIdSet.size;
    ztoolkit.log(
      `[ZoFiles] Rebuilding ${total} items across ${allNodes.length} collections`,
    );

    // Export items sequentially for clear progress reporting
    const errors: string[] = [];
    let exported = 0;
    let current = 0;

    for (const itemId of itemIdSet) {
      current++;

      // Peek at item metadata for progress reporting
      let arxivIdForProgress = "unknown";
      let titleForProgress = "";
      try {
        const item = Zotero.Items.get(itemId);
        if (item) {
          arxivIdForProgress = extractArxivId(item) || "unknown";
          if (arxivIdForProgress !== "unknown") {
            arxivIdForProgress = stripVersion(arxivIdForProgress);
          }
          titleForProgress = String(item.getField("title") || "");
        }
      } catch {
        // Ignore errors peeking at item
      }

      // Report progress: exporting
      if (onProgress) {
        onProgress({
          current,
          total,
          arxivId: arxivIdForProgress,
          title: titleForProgress,
          status: "exporting",
        });
      }

      try {
        await this.doExportItem(itemId, tree);
        exported++;
        if (onProgress) {
          onProgress({
            current,
            total,
            arxivId: arxivIdForProgress,
            title: titleForProgress,
            status: "done",
          });
        }
      } catch (err: any) {
        errors.push(`Item ${itemId}: ${err.message || err}`);
        if (onProgress) {
          onProgress({
            current,
            total,
            arxivId: arxivIdForProgress,
            title: titleForProgress,
            status: "error",
          });
        }
      }
    }

    // Persist the index
    await this.saveIndex(exportRoot);

    ztoolkit.log(
      `[ZoFiles] Full rebuild complete: ${exported} exported, ${errors.length} errors`,
    );

    return { exported, errors };
  }

  /**
   * Export a single item to all its collection paths.
   * Called for incremental updates (item added/modified, attachment changed).
   * Debounced and deduped via the ExportQueue.
   */
  async exportItem(itemId: number): Promise<void> {
    return this.exportQueue.enqueue(itemId);
  }

  /**
   * Remove all exported files for one or more items.
   * Called when items are trashed, deleted, or removed from all collections.
   */
  async removeItemExport(itemIds: number[]): Promise<void> {
    const exportRoot = getExportRoot();
    if (!exportRoot) return;

    const index = await this.loadIndex(exportRoot);

    for (const itemId of itemIds) {
      const entry = index.entries[String(itemId)];
      if (!entry) continue;

      ztoolkit.log(`[ZoFiles] Removing export for item ${itemId}`);

      // Remove all exported paper directories
      for (const exportedPath of entry.exportedPaths) {
        const paperDir = joinPath(exportedPath, entry.folderName);
        try {
          await removeDir(paperDir);
        } catch (e: any) {
          ztoolkit.log(`[ZoFiles] Failed to remove ${paperDir}: ${e.message}`);
        }
      }

      // Remove from index
      delete index.entries[String(itemId)];
    }

    await this.saveIndex(exportRoot);
  }

  // -------------------------------------------------------------------------
  // Internal export logic
  // -------------------------------------------------------------------------

  /**
   * Core export logic for a single item.
   *
   * 1. Validate item and extract arXiv ID
   * 2. Build (or reuse) the collection tree
   * 3. Resolve all target directories for this item
   * 4. Create the paper folder in the primary location
   * 5. Run every enabled content provider sequentially
   * 6. Copy the paper folder to additional locations
   * 7. Optionally link generated files back to Zotero
   * 8. Update the on-disk index
   *
   * @param itemId       The Zotero item ID
   * @param prebuiltTree Optional pre-built tree to avoid per-item rebuilds
   */
  private async doExportItem(
    itemId: number,
    prebuiltTree?: CollectionNode[],
  ): Promise<void> {
    const exportRoot = getExportRoot();
    if (!exportRoot) {
      throw new Error("Export root path is not configured");
    }

    // Get the Zotero item
    const item = Zotero.Items.get(itemId);
    if (!item || !item.isRegularItem()) return;

    // Extract arXiv ID — skip items without one
    const rawArxivId = extractArxivId(item);
    if (!rawArxivId) {
      ztoolkit.log(`[ZoFiles] Skipping item ${itemId}: no arXiv ID found`);
      return;
    }
    const arxivId = stripVersion(rawArxivId);

    // Build paper folder name using the user's template + item metadata
    const folderName = formatPaperFolder(item, arxivId);

    // Determine per-paper cache directory and ensure it exists
    const cacheDir = getCachePath(arxivId);
    await ensureDir(cacheDir);

    // Build or reuse the collection tree
    const tree = prebuiltTree || (await buildCollectionTree());

    // Resolve all target directories for this item
    const targetDirs = resolveItemPaths(itemId, tree, exportRoot);
    if (targetDirs.length === 0) {
      ztoolkit.log(
        `[ZoFiles] Item ${itemId} (${arxivId}) not in any exported collection, skipping`,
      );

      // Log diagnostic info to help debug
      const collections = item.getCollections();
      ztoolkit.log(`[ZoFiles]   Item collections: [${collections.join(", ")}]`);
      const enabledJson = getPref("enabledCollections") as string;
      ztoolkit.log(`[ZoFiles]   enabledCollections pref: ${enabledJson}`);
      return;
    }

    // Get enabled content providers
    const providers = getEnabledProviders();
    if (providers.length === 0) return;

    ztoolkit.log(
      `[ZoFiles] Exporting ${arxivId} (item ${itemId}) to ${targetDirs.length} location(s)`,
    );
    for (const dir of targetDirs) {
      ztoolkit.log(`[ZoFiles]   → ${dir}`);
    }

    // ------ Primary copy: export to the first target directory ------
    const primaryDir = targetDirs[0];
    // Ensure the entire directory chain exists (collection dirs + paper dir)
    await ensureDir(primaryDir);
    const paperDir = joinPath(primaryDir, folderName);
    await ensureDir(paperDir);

    const ctx: ExportContext = {
      item,
      arxivId,
      paperDir,
      cacheDir,
    };

    // Run all providers sequentially (order matters — fast first)
    const allFiles: string[] = [];
    const linkBackFiles: string[] = [];

    for (const provider of providers) {
      try {
        const result: ProviderResult = await provider.export(ctx);
        if (result.success) {
          allFiles.push(...result.files);
          if (result.linkBack) {
            linkBackFiles.push(...result.files);
          }
        } else if (result.error) {
          ztoolkit.log(
            `[ZoFiles] Provider ${provider.id} failed for ${arxivId}: ${result.error}`,
          );
        }
      } catch (e: any) {
        ztoolkit.log(
          `[ZoFiles] Provider ${provider.id} threw for ${arxivId}: ${e.message}`,
        );
      }
    }

    ztoolkit.log(
      `[ZoFiles] Exported ${arxivId}: ${allFiles.length} files to ${paperDir}`,
    );

    // ------ Additional copies: duplicate the paper folder ------
    const allExportedPaths = [primaryDir];
    for (let i = 1; i < targetDirs.length; i++) {
      const targetDir = targetDirs[i];
      const targetPaperDir = joinPath(targetDir, folderName);
      try {
        await ensureDir(targetDir);
        await copyDirectory(paperDir, targetPaperDir);
        allExportedPaths.push(targetDir);
      } catch (e: any) {
        ztoolkit.log(
          `[ZoFiles] Failed to copy to ${targetPaperDir}: ${e.message}`,
        );
      }
    }

    // ------ Link back to Zotero ------
    const linkBack = getPref("linkBackToZotero") as boolean;
    if (linkBack && linkBackFiles.length > 0) {
      await this.linkResultsToZotero(item, linkBackFiles);
    }

    // ------ Clean up stale paths from previous export ------
    const index = await this.loadIndex(exportRoot);
    const prevEntry = index.entries[String(itemId)];
    if (prevEntry) {
      // Find paths that were in the old export but are NOT in the new export
      const newPathSet = new Set(allExportedPaths);
      for (const oldPath of prevEntry.exportedPaths) {
        if (!newPathSet.has(oldPath)) {
          const stalePaperDir = joinPath(oldPath, prevEntry.folderName);
          ztoolkit.log(
            `[ZoFiles] Cleaning stale path for ${arxivId}: ${stalePaperDir}`,
          );
          try {
            await removeDir(stalePaperDir);
          } catch {
            // Ignore — folder may already be gone
          }
        }
      }
      // Also handle folder name change: old folder name at current paths
      if (prevEntry.folderName !== folderName) {
        for (const oldPath of prevEntry.exportedPaths) {
          const oldPaperDir = joinPath(oldPath, prevEntry.folderName);
          ztoolkit.log(
            `[ZoFiles] Cleaning old folder name for ${arxivId}: ${oldPaperDir}`,
          );
          try {
            await removeDir(oldPaperDir);
          } catch {
            // Ignore
          }
        }
      }
    }

    // ------ Update index ------
    index.entries[String(itemId)] = {
      itemId,
      arxivId,
      folderName,
      exportedPaths: allExportedPaths,
      files: allFiles.map((f) => f.replace(paperDir, "").replace(/^[/\\]/, "")),
      lastExported: Date.now(),
    };
    await this.saveIndex(exportRoot);
  }

  // -------------------------------------------------------------------------
  // Link-back to Zotero
  // -------------------------------------------------------------------------

  /**
   * Link generated files back to the Zotero item as linked file attachments.
   * Skips files that already exist as attachments (checks by file path).
   * Titles are prefixed with "[ZoFiles]" for easy identification.
   */
  private async linkResultsToZotero(
    item: Zotero.Item,
    filePaths: string[],
  ): Promise<void> {
    // Collect existing ZoFiles attachment titles AND paths to avoid duplicates.
    // We match by title prefix "[ZoFiles] <filename>" because file paths change
    // when items move between collections, causing path-only matching to fail
    // and create duplicate attachments.
    const existingTitles = new Set<string>();
    const existingPaths = new Set<string>();
    const staleAttachmentIds: number[] = [];
    const attachmentIds = item.getAttachments();

    for (const attId of attachmentIds) {
      const att = Zotero.Items.get(attId);
      if (!att || !att.isAttachment()) continue;

      const title = String(att.getField("title") || "");
      if (title.startsWith("[ZoFiles] ")) {
        existingTitles.add(title);

        // Check if the linked file still exists; if not, it's stale
        // (from a previous path that was cleaned up)
        try {
          const path = await att.getFilePathAsync();
          if (path) {
            const fileExists = await IOUtils.exists(path);
            if (fileExists) {
              existingPaths.add(path);
            } else {
              // Stale link — file no longer exists at old path
              staleAttachmentIds.push(attId);
            }
          } else {
            staleAttachmentIds.push(attId);
          }
        } catch {
          staleAttachmentIds.push(attId);
        }
      }
    }

    // Remove stale [ZoFiles] attachments whose files no longer exist
    for (const attId of staleAttachmentIds) {
      try {
        const att = Zotero.Items.get(attId);
        if (att) {
          ztoolkit.log(
            `[ZoFiles] Removing stale link-back attachment ${attId} from item ${item.id}`,
          );
          await att.eraseTx();
        }
      } catch (e: any) {
        ztoolkit.log(
          `[ZoFiles] Failed to remove stale attachment ${attId}: ${e.message}`,
        );
      }
    }

    // Re-collect titles after cleanup (stale ones removed)
    if (staleAttachmentIds.length > 0) {
      existingTitles.clear();
      const refreshedIds = item.getAttachments();
      for (const attId of refreshedIds) {
        const att = Zotero.Items.get(attId);
        if (!att || !att.isAttachment()) continue;
        const title = String(att.getField("title") || "");
        if (title.startsWith("[ZoFiles] ")) {
          existingTitles.add(title);
        }
      }
    }

    for (const filePath of filePaths) {
      const fileName = PathUtils.filename(filePath);
      const expectedTitle = `[ZoFiles] ${fileName}`;

      // Skip if already linked (by title or by exact path)
      if (existingTitles.has(expectedTitle) || existingPaths.has(filePath)) {
        continue;
      }

      // Verify the file actually exists on disk
      const exists = await IOUtils.exists(filePath);
      if (!exists) continue;

      try {
        await Zotero.Attachments.linkFromFile({
          file: filePath,
          parentItemID: item.id,
          title: expectedTitle,
        });
        existingTitles.add(expectedTitle);
        ztoolkit.log(`[ZoFiles] Linked ${fileName} back to item ${item.id}`);
      } catch (e: any) {
        ztoolkit.log(
          `[ZoFiles] Failed to link ${filePath} to item ${item.id}: ${e.message}`,
        );
      }
    }
  }

  // -------------------------------------------------------------------------
  // Index management
  // -------------------------------------------------------------------------

  /**
   * Load the export index from disk, or return the cached version.
   * The index maps itemId → { paths, files, timestamps } for incremental
   * removal and re-export decisions.
   */
  async loadIndex(exportRoot: string): Promise<ExportIndex> {
    if (this.indexCache) return this.indexCache;

    const indexPath = joinPath(exportRoot, ".zofiles-index.json");
    try {
      const exists = await IOUtils.exists(indexPath);
      if (!exists) {
        this.indexCache = createEmptyIndex();
        return this.indexCache;
      }

      const bytes = await IOUtils.read(indexPath);
      const text = new TextDecoder().decode(bytes);
      const parsed = JSON.parse(text) as ExportIndex;

      // Validate schema version
      if (parsed.version !== 1) {
        ztoolkit.log(
          `[ZoFiles] Index version mismatch (${parsed.version}), creating new index`,
        );
        this.indexCache = createEmptyIndex();
        return this.indexCache;
      }

      this.indexCache = parsed;
      return this.indexCache;
    } catch (e: any) {
      ztoolkit.log(
        `[ZoFiles] Failed to load index: ${e.message}, creating new`,
      );
      this.indexCache = createEmptyIndex();
      return this.indexCache;
    }
  }

  /**
   * Save the export index to disk atomically (write to temp, then rename).
   */
  async saveIndex(exportRoot: string): Promise<void> {
    if (!this.indexCache) return;

    const indexPath = joinPath(exportRoot, ".zofiles-index.json");
    const tmpPath = indexPath + ".tmp";

    try {
      const json = JSON.stringify(this.indexCache, null, 2);
      const content = new TextEncoder().encode(json);
      await IOUtils.write(tmpPath, content);
      await IOUtils.move(tmpPath, indexPath);
    } catch (e: any) {
      ztoolkit.log(`[ZoFiles] Failed to save index: ${e.message}`);
      // Clean up temp file on failure
      try {
        await IOUtils.remove(tmpPath, { ignoreAbsent: true });
      } catch {
        // Ignore
      }
    }
  }

  /**
   * Invalidate the in-memory index cache, forcing a reload on next access.
   */
  invalidateIndexCache(): void {
    this.indexCache = null;
  }

  /**
   * Rebase the index when the export root directory has been moved.
   *
   * Rewrites all `exportedPaths` in the index, replacing `oldRoot` with
   * `newRoot`. This avoids the need for a full rebuild after the user
   * moves the export directory to a different location.
   *
   * @returns The number of entries updated, or -1 if the old index was not found.
   */
  async rebaseIndex(oldRoot: string, newRoot: string): Promise<number> {
    // Try loading the index from the new location first (user may have
    // already moved the directory, so .zofiles-index.json is there).
    let indexPath = joinPath(newRoot, ".zofiles-index.json");
    let exists = await IOUtils.exists(indexPath);

    if (!exists) {
      // Maybe the index hasn't been moved — try old location
      indexPath = joinPath(oldRoot, ".zofiles-index.json");
      exists = await IOUtils.exists(indexPath);
      if (!exists) {
        ztoolkit.log(
          "[ZoFiles] rebaseIndex: no index found at old or new root",
        );
        return -1;
      }
      // Copy the index file to the new root
      const newIndexPath = joinPath(newRoot, ".zofiles-index.json");
      await ensureDir(newRoot);
      await IOUtils.copy(indexPath, newIndexPath);
      indexPath = newIndexPath;
    }

    // Invalidate cache and load from the new location
    this.indexCache = null;
    const index = await this.loadIndex(newRoot);

    // Normalise trailing separators for reliable prefix replacement
    const oldPrefix = oldRoot.replace(/[/\\]+$/, "");
    const newPrefix = newRoot.replace(/[/\\]+$/, "");

    let updated = 0;
    for (const entry of Object.values(index.entries)) {
      const rewritten: string[] = [];
      let changed = false;
      for (const p of entry.exportedPaths) {
        if (
          p === oldPrefix ||
          p.startsWith(oldPrefix + "/") ||
          p.startsWith(oldPrefix + "\\")
        ) {
          rewritten.push(newPrefix + p.slice(oldPrefix.length));
          changed = true;
        } else {
          rewritten.push(p);
        }
      }
      if (changed) {
        entry.exportedPaths = rewritten;
        updated++;
      }
    }

    if (updated > 0) {
      await this.saveIndex(newRoot);
      ztoolkit.log(
        `[ZoFiles] rebaseIndex: updated ${updated} entries from ${oldPrefix} → ${newPrefix}`,
      );
    } else {
      ztoolkit.log("[ZoFiles] rebaseIndex: no entries needed updating");
    }

    return updated;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Create a fresh empty index.
 */
function createEmptyIndex(): ExportIndex {
  return { version: 1, entries: {} };
}

/**
 * Recursively copy a directory to a new location.
 * Used when an item appears in multiple collections and needs identical
 * paper folders in each location.
 */
async function copyDirectory(src: string, dest: string): Promise<void> {
  await ensureDir(dest);

  const children = await IOUtils.getChildren(src);
  for (const childPath of children) {
    const name = PathUtils.filename(childPath);
    const destChild = joinPath(dest, name);

    const info = await IOUtils.stat(childPath);
    if (info.type === "directory") {
      await copyDirectory(childPath, destChild);
    } else {
      await IOUtils.copy(childPath, destChild);
    }
  }
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

let _exporter: Exporter | null = null;

/**
 * Get the singleton Exporter instance.
 */
export function getExporter(): Exporter {
  if (!_exporter) {
    _exporter = new Exporter();
  }
  return _exporter;
}

/**
 * Reset the singleton (used during plugin shutdown or testing).
 */
export function resetExporter(): void {
  _exporter = null;
}
